### ISSUE TITLE
Need to maintain the object repository to handle the data

### ISSUE THREAD

**Issue by akashbarla5** [rajeshp7/gramenertest#19]
It will be easy to handle the data or modify the data if we maintain the object repository file.

**Comment by rajeshp7** [comment]
@akashbarla5 I didn't get the issue. Please explain in detail

**Comment by akashbarla5** [comment]
@rajeshp7 
For ex: I need to verify the logo/ title in 3 dashboards. So, I need to pass the selector in 3 different places. In this case, if we maintain the object repository we can pass the selector in single place instead of multiple places. In case the selector is changed in future it will be easy to modify.

**Comment by rajeshp7** [comment]
object repository is being maintained separately
