### ISSUE TITLE
In one script,multiple test cases should be covered.

### ISSUE THREAD

**Issue by Shubhra2102** [rajeshp7/gramenertest#24]
In one script,multiple test cases should be covered.So that we can cover a module (if possible) in a script with less no. of lines of code and maintenance will be less after new change

**Comment by rajeshp7** [comment]
@Shubhra2102 could you please check the existing functionality and confirm?

**Comment by Shubhra2102** [comment]
Yes, now we can execute multiple test cases in one script.
