### ISSUE TITLE
Able to select the option by name from the drop down

### ISSUE THREAD

**Issue by akashbarla5** [rajeshp7/gramenertest#28]
Need to have flexibility to select the option from drop down by option name

For ex: In State drop down we will have list of states. So, we can able to select option using State name

**Comment by rajeshp7** [comment]
added function to select an option using value, text and index.
@akashbarla5 please test and confirm

**Comment by akashbarla5** [comment]
Working fine @rajeshp7

**Comment by rajeshp7** [comment]
thank you
