### ISSUE TITLE
Able to hover on the option to click on it

### ISSUE THREAD

**Issue by akashbarla5** [rajeshp7/gramenertest#29]
Able to select  by hovering on the option.

For ex:

In my project I have 3 sub tabs under one main dashboard tab. These 3 sub tabs will be visible only when I hover on dashboard tab(click won't work here in this case).

**Comment by rajeshp7** [comment]
@akashbarla5 please add a gif or screenshot

**Comment by akashbarla5** [comment]
Please find the below recording for the same and let me know if you need any further information

![hover](https://user-images.githubusercontent.com/70646283/94696743-01aab400-0355-11eb-8d1f-b8b8a1b1ff7a.gif)

**Comment by rajeshp7** [comment]
@akashbarla5 hover method has been added. please test and confirm

**Comment by akashbarla5** [comment]
Working fine Rajesh
