### ISSUE TITLE
Storing table values in a variable 

### ISSUE THREAD

**Issue by PrashanthKumar-S** [rajeshp7/gramenertest#30]
The user should be able to store table values in the variable
If there are multiple values, the user should be able to perform sort action.

![image](https://user-images.githubusercontent.com/41776401/95174131-414f2100-07d7-11eb-93f7-2fb0495871a0.png)

![image](https://user-images.githubusercontent.com/41776401/95173925-fc2aef00-07d6-11eb-8299-1d409af1731e.png)

**Comment by rajeshp7** [comment]
multiple values will be stored as a list of lists in a variable
