### ISSUE TITLE
Usage of Jquery/ Javascript commands in test scripts or test objects

### ISSUE THREAD

**Issue by PrashanthKumar-S** [rajeshp7/gramenertest#31]
I want to implement a logic where I could read the attribute value which changes dynamically. Is it possible if we could use jQuery or JavaScript methods to read the attribute values in HTML element and perform loop or conditional statements.

![image](https://user-images.githubusercontent.com/41776401/95174551-db16ce00-07d7-11eb-8084-4dbd5abb4274.png)

**Comment by rajeshp7** [comment]
script method has been added
