### ISSUE TITLE
Need to verify the presence of visual or no data

### ISSUE THREAD

**Issue by akashbarla5** [rajeshp7/gramenertest#37]

**Comment by rajeshp7** [comment]
@akashbarla5 please provide an example

**Comment by akashbarla5** [comment]
For example in Exp Trend view, If we have data trend will be displayed for selected entry

![image](https://user-images.githubusercontent.com/70646283/97415933-cedfe580-192b-11eb-8d8d-2757df599d3c.png)

When there is no data for selected combination , instead of trend No Data image will be displayed

![image](https://user-images.githubusercontent.com/70646283/97416033-edde7780-192b-11eb-92f6-37b803afd145.png)

**Comment by akashbarla5** [comment]
@rajeshp7  Please let me know if you need any further information on this issue

**Comment by akashbarla5** [comment]
Added a method called attribute to validate the visuals and no data
